targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          #compiler: dartdevc
          compiler: dart2js
          dart2js_args:
            - --fast-startup
            #- --minify
            - --omit-implicit-checks
