name: plato.archives
description: An archived courses viewer for Plato.
version: 0.16.4+3

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.69.2 <2.0.0'

dependencies:
  angular: ^5.0.0-beta+2
  angular_components: ^0.9.0-beta+1

dev_dependencies:
  angular_test: ^2.0.0-beta+2
  build_runner: ^0.9.2
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  test: ^1.3.0
