name: plato.archives
description: An archived courses viewer for Plato.
version: 0.16.4+3

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.68.0 <2.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.1
  build_test: ^0.10.3
  build_web_compilers: ^0.4.0+4
  test: ^1.2.0
