name: plato.archives
description: A course archives viewer for Plato.
version: 0.16.4

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0-dev.66.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+15
  angular_components: ^0.9.0-alpha+15

dev_dependencies:
  angular_test: ^2.0.0-alpha+13
  build_runner: ^0.9.1
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  test: ^1.2.0
