name: plato.archives
description: An archived courses viewer for Plato.
version: 0.17.4

author: Joseph B. Axenroth

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  http: ^0.12.0+2

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.5
  build_test: ^0.10.8
  build_web_compilers: ^2.1.5
  sass_builder: ^2.1.3
  test: ^1.6.3
