name: plato.archives
description: An archived courses viewer for Plato.
version: 0.16.6+4

author: Joseph B. Axenroth

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  http: ^0.11.3+17

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.1
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.2
  sass_builder: ^2.1.1
  test: ^1.3.0
