library plato.archives.caching.registry;

/// The [Registry] class...
abstract class Registry<S, T> {
  /// The [register] method...
  void register (S key, T resource);

  /// The [unregister] method...
  T unregister (S key);

  /// The [retrieve] method...
  T retrieve (S key);

  /// The [refresh] method...
  T refresh (S key, T newResource);

  /// The [contains] method...
  bool contains (S key);

  /// The [isEmpty] method...
  bool isEmpty();

  /// The [clear] method...
  void clear();
}
